# Generated by Django 6.0.6 on 2026-06-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_remove_ticker_asset_type_alter_ticker_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('BACKTEST', 'Backtest'), ('SIGNAL', 'Signal scan')], default='BACKTEST', max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('ticker_symbol', models.CharField(default='XAUUSD', max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(default='60d', max_length=16)),
                ('interval', models.CharField(default='15m', max_length=16)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'price history'},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'trade history'},
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='source',
            field=models.CharField(default='BOT', max_length=24),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='symbol',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='side',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('RESULT', 'Result')], max_length=10),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='bot_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='market_data.botrun'),
        ),
    ]
